### ISSUE TITLE
Convert .acignore to .gitignore

### ISSUE THREAD

**Issue by veljkosbbb** [fuzzmz/accurev-to-git#1]
Hi,

is there already implemented method/script that converts automatically or at least partially **.acignore** file to **.gitignore** file?
Can you please give us details how this could be achieved?

Thanks a lot!

**Comment by fuzzmz** [comment]
Hi @veljkosbbb. Unfortunately I haven't had to deal with AccuRev for some time now, so I'm unaware of something like that. From what I remember though, the patterns for .acignore ar the same as .gitignore, so they could be in theory translated just by renaming the .acignore file (if in source control) to .gitignore.

Granted, this needs some extra handling for example during .acignore updates. How I'd do it is, if after finishing to transition all AccuRev history to git we find one or more .acignore files in the repo rename them to .gitignore.
